// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: activity/activity.proto

package activityconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	activity "github.com/mas-soft/masflow-sdk/internal/pb/activity"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ModuleRegistryName is the fully-qualified name of the ModuleRegistry service.
	ModuleRegistryName = "activity.ModuleRegistry"
	// ActivityExecutorName is the fully-qualified name of the ActivityExecutor service.
	ActivityExecutorName = "activity.ActivityExecutor"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ModuleRegistryRegisterModuleProcedure is the fully-qualified name of the ModuleRegistry's
	// RegisterModule RPC.
	ModuleRegistryRegisterModuleProcedure = "/activity.ModuleRegistry/RegisterModule"
	// ModuleRegistryUnregisterModuleProcedure is the fully-qualified name of the ModuleRegistry's
	// UnregisterModule RPC.
	ModuleRegistryUnregisterModuleProcedure = "/activity.ModuleRegistry/UnregisterModule"
	// ModuleRegistryListModulesProcedure is the fully-qualified name of the ModuleRegistry's
	// ListModules RPC.
	ModuleRegistryListModulesProcedure = "/activity.ModuleRegistry/ListModules"
	// ModuleRegistryGetModuleProcedure is the fully-qualified name of the ModuleRegistry's GetModule
	// RPC.
	ModuleRegistryGetModuleProcedure = "/activity.ModuleRegistry/GetModule"
	// ModuleRegistryListActivitiesProcedure is the fully-qualified name of the ModuleRegistry's
	// ListActivities RPC.
	ModuleRegistryListActivitiesProcedure = "/activity.ModuleRegistry/ListActivities"
	// ModuleRegistryGetActivityProcedure is the fully-qualified name of the ModuleRegistry's
	// GetActivity RPC.
	ModuleRegistryGetActivityProcedure = "/activity.ModuleRegistry/GetActivity"
	// ActivityExecutorExecuteProcedure is the fully-qualified name of the ActivityExecutor's Execute
	// RPC.
	ActivityExecutorExecuteProcedure = "/activity.ActivityExecutor/Execute"
)

// ModuleRegistryClient is a client for the activity.ModuleRegistry service.
type ModuleRegistryClient interface {
	RegisterModule(context.Context, *connect.Request[activity.RegisterModuleRequest]) (*connect.Response[activity.RegisterModuleResponse], error)
	UnregisterModule(context.Context, *connect.Request[activity.UnregisterModuleRequest]) (*connect.Response[activity.UnregisterModuleResponse], error)
	ListModules(context.Context, *connect.Request[activity.ListModulesRequest]) (*connect.Response[activity.ListModulesResponse], error)
	GetModule(context.Context, *connect.Request[activity.GetModuleRequest]) (*connect.Response[activity.GetModuleResponse], error)
	ListActivities(context.Context, *connect.Request[activity.ListActivitiesRequest]) (*connect.Response[activity.ListActivitiesResponse], error)
	GetActivity(context.Context, *connect.Request[activity.GetActivityRequest]) (*connect.Response[activity.GetActivityResponse], error)
}

// NewModuleRegistryClient constructs a client for the activity.ModuleRegistry service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewModuleRegistryClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ModuleRegistryClient {
	baseURL = strings.TrimRight(baseURL, "/")
	moduleRegistryMethods := activity.File_activity_activity_proto.Services().ByName("ModuleRegistry").Methods()
	return &moduleRegistryClient{
		registerModule: connect.NewClient[activity.RegisterModuleRequest, activity.RegisterModuleResponse](
			httpClient,
			baseURL+ModuleRegistryRegisterModuleProcedure,
			connect.WithSchema(moduleRegistryMethods.ByName("RegisterModule")),
			connect.WithClientOptions(opts...),
		),
		unregisterModule: connect.NewClient[activity.UnregisterModuleRequest, activity.UnregisterModuleResponse](
			httpClient,
			baseURL+ModuleRegistryUnregisterModuleProcedure,
			connect.WithSchema(moduleRegistryMethods.ByName("UnregisterModule")),
			connect.WithClientOptions(opts...),
		),
		listModules: connect.NewClient[activity.ListModulesRequest, activity.ListModulesResponse](
			httpClient,
			baseURL+ModuleRegistryListModulesProcedure,
			connect.WithSchema(moduleRegistryMethods.ByName("ListModules")),
			connect.WithClientOptions(opts...),
		),
		getModule: connect.NewClient[activity.GetModuleRequest, activity.GetModuleResponse](
			httpClient,
			baseURL+ModuleRegistryGetModuleProcedure,
			connect.WithSchema(moduleRegistryMethods.ByName("GetModule")),
			connect.WithClientOptions(opts...),
		),
		listActivities: connect.NewClient[activity.ListActivitiesRequest, activity.ListActivitiesResponse](
			httpClient,
			baseURL+ModuleRegistryListActivitiesProcedure,
			connect.WithSchema(moduleRegistryMethods.ByName("ListActivities")),
			connect.WithClientOptions(opts...),
		),
		getActivity: connect.NewClient[activity.GetActivityRequest, activity.GetActivityResponse](
			httpClient,
			baseURL+ModuleRegistryGetActivityProcedure,
			connect.WithSchema(moduleRegistryMethods.ByName("GetActivity")),
			connect.WithClientOptions(opts...),
		),
	}
}

// moduleRegistryClient implements ModuleRegistryClient.
type moduleRegistryClient struct {
	registerModule   *connect.Client[activity.RegisterModuleRequest, activity.RegisterModuleResponse]
	unregisterModule *connect.Client[activity.UnregisterModuleRequest, activity.UnregisterModuleResponse]
	listModules      *connect.Client[activity.ListModulesRequest, activity.ListModulesResponse]
	getModule        *connect.Client[activity.GetModuleRequest, activity.GetModuleResponse]
	listActivities   *connect.Client[activity.ListActivitiesRequest, activity.ListActivitiesResponse]
	getActivity      *connect.Client[activity.GetActivityRequest, activity.GetActivityResponse]
}

// RegisterModule calls activity.ModuleRegistry.RegisterModule.
func (c *moduleRegistryClient) RegisterModule(ctx context.Context, req *connect.Request[activity.RegisterModuleRequest]) (*connect.Response[activity.RegisterModuleResponse], error) {
	return c.registerModule.CallUnary(ctx, req)
}

// UnregisterModule calls activity.ModuleRegistry.UnregisterModule.
func (c *moduleRegistryClient) UnregisterModule(ctx context.Context, req *connect.Request[activity.UnregisterModuleRequest]) (*connect.Response[activity.UnregisterModuleResponse], error) {
	return c.unregisterModule.CallUnary(ctx, req)
}

// ListModules calls activity.ModuleRegistry.ListModules.
func (c *moduleRegistryClient) ListModules(ctx context.Context, req *connect.Request[activity.ListModulesRequest]) (*connect.Response[activity.ListModulesResponse], error) {
	return c.listModules.CallUnary(ctx, req)
}

// GetModule calls activity.ModuleRegistry.GetModule.
func (c *moduleRegistryClient) GetModule(ctx context.Context, req *connect.Request[activity.GetModuleRequest]) (*connect.Response[activity.GetModuleResponse], error) {
	return c.getModule.CallUnary(ctx, req)
}

// ListActivities calls activity.ModuleRegistry.ListActivities.
func (c *moduleRegistryClient) ListActivities(ctx context.Context, req *connect.Request[activity.ListActivitiesRequest]) (*connect.Response[activity.ListActivitiesResponse], error) {
	return c.listActivities.CallUnary(ctx, req)
}

// GetActivity calls activity.ModuleRegistry.GetActivity.
func (c *moduleRegistryClient) GetActivity(ctx context.Context, req *connect.Request[activity.GetActivityRequest]) (*connect.Response[activity.GetActivityResponse], error) {
	return c.getActivity.CallUnary(ctx, req)
}

// ModuleRegistryHandler is an implementation of the activity.ModuleRegistry service.
type ModuleRegistryHandler interface {
	RegisterModule(context.Context, *connect.Request[activity.RegisterModuleRequest]) (*connect.Response[activity.RegisterModuleResponse], error)
	UnregisterModule(context.Context, *connect.Request[activity.UnregisterModuleRequest]) (*connect.Response[activity.UnregisterModuleResponse], error)
	ListModules(context.Context, *connect.Request[activity.ListModulesRequest]) (*connect.Response[activity.ListModulesResponse], error)
	GetModule(context.Context, *connect.Request[activity.GetModuleRequest]) (*connect.Response[activity.GetModuleResponse], error)
	ListActivities(context.Context, *connect.Request[activity.ListActivitiesRequest]) (*connect.Response[activity.ListActivitiesResponse], error)
	GetActivity(context.Context, *connect.Request[activity.GetActivityRequest]) (*connect.Response[activity.GetActivityResponse], error)
}

// NewModuleRegistryHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewModuleRegistryHandler(svc ModuleRegistryHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	moduleRegistryMethods := activity.File_activity_activity_proto.Services().ByName("ModuleRegistry").Methods()
	moduleRegistryRegisterModuleHandler := connect.NewUnaryHandler(
		ModuleRegistryRegisterModuleProcedure,
		svc.RegisterModule,
		connect.WithSchema(moduleRegistryMethods.ByName("RegisterModule")),
		connect.WithHandlerOptions(opts...),
	)
	moduleRegistryUnregisterModuleHandler := connect.NewUnaryHandler(
		ModuleRegistryUnregisterModuleProcedure,
		svc.UnregisterModule,
		connect.WithSchema(moduleRegistryMethods.ByName("UnregisterModule")),
		connect.WithHandlerOptions(opts...),
	)
	moduleRegistryListModulesHandler := connect.NewUnaryHandler(
		ModuleRegistryListModulesProcedure,
		svc.ListModules,
		connect.WithSchema(moduleRegistryMethods.ByName("ListModules")),
		connect.WithHandlerOptions(opts...),
	)
	moduleRegistryGetModuleHandler := connect.NewUnaryHandler(
		ModuleRegistryGetModuleProcedure,
		svc.GetModule,
		connect.WithSchema(moduleRegistryMethods.ByName("GetModule")),
		connect.WithHandlerOptions(opts...),
	)
	moduleRegistryListActivitiesHandler := connect.NewUnaryHandler(
		ModuleRegistryListActivitiesProcedure,
		svc.ListActivities,
		connect.WithSchema(moduleRegistryMethods.ByName("ListActivities")),
		connect.WithHandlerOptions(opts...),
	)
	moduleRegistryGetActivityHandler := connect.NewUnaryHandler(
		ModuleRegistryGetActivityProcedure,
		svc.GetActivity,
		connect.WithSchema(moduleRegistryMethods.ByName("GetActivity")),
		connect.WithHandlerOptions(opts...),
	)
	return "/activity.ModuleRegistry/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ModuleRegistryRegisterModuleProcedure:
			moduleRegistryRegisterModuleHandler.ServeHTTP(w, r)
		case ModuleRegistryUnregisterModuleProcedure:
			moduleRegistryUnregisterModuleHandler.ServeHTTP(w, r)
		case ModuleRegistryListModulesProcedure:
			moduleRegistryListModulesHandler.ServeHTTP(w, r)
		case ModuleRegistryGetModuleProcedure:
			moduleRegistryGetModuleHandler.ServeHTTP(w, r)
		case ModuleRegistryListActivitiesProcedure:
			moduleRegistryListActivitiesHandler.ServeHTTP(w, r)
		case ModuleRegistryGetActivityProcedure:
			moduleRegistryGetActivityHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedModuleRegistryHandler returns CodeUnimplemented from all methods.
type UnimplementedModuleRegistryHandler struct{}

func (UnimplementedModuleRegistryHandler) RegisterModule(context.Context, *connect.Request[activity.RegisterModuleRequest]) (*connect.Response[activity.RegisterModuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("activity.ModuleRegistry.RegisterModule is not implemented"))
}

func (UnimplementedModuleRegistryHandler) UnregisterModule(context.Context, *connect.Request[activity.UnregisterModuleRequest]) (*connect.Response[activity.UnregisterModuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("activity.ModuleRegistry.UnregisterModule is not implemented"))
}

func (UnimplementedModuleRegistryHandler) ListModules(context.Context, *connect.Request[activity.ListModulesRequest]) (*connect.Response[activity.ListModulesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("activity.ModuleRegistry.ListModules is not implemented"))
}

func (UnimplementedModuleRegistryHandler) GetModule(context.Context, *connect.Request[activity.GetModuleRequest]) (*connect.Response[activity.GetModuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("activity.ModuleRegistry.GetModule is not implemented"))
}

func (UnimplementedModuleRegistryHandler) ListActivities(context.Context, *connect.Request[activity.ListActivitiesRequest]) (*connect.Response[activity.ListActivitiesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("activity.ModuleRegistry.ListActivities is not implemented"))
}

func (UnimplementedModuleRegistryHandler) GetActivity(context.Context, *connect.Request[activity.GetActivityRequest]) (*connect.Response[activity.GetActivityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("activity.ModuleRegistry.GetActivity is not implemented"))
}

// ActivityExecutorClient is a client for the activity.ActivityExecutor service.
type ActivityExecutorClient interface {
	Execute(context.Context, *connect.Request[activity.ExecuteActivityRequest]) (*connect.Response[activity.ExecuteActivityResponse], error)
}

// NewActivityExecutorClient constructs a client for the activity.ActivityExecutor service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewActivityExecutorClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ActivityExecutorClient {
	baseURL = strings.TrimRight(baseURL, "/")
	activityExecutorMethods := activity.File_activity_activity_proto.Services().ByName("ActivityExecutor").Methods()
	return &activityExecutorClient{
		execute: connect.NewClient[activity.ExecuteActivityRequest, activity.ExecuteActivityResponse](
			httpClient,
			baseURL+ActivityExecutorExecuteProcedure,
			connect.WithSchema(activityExecutorMethods.ByName("Execute")),
			connect.WithClientOptions(opts...),
		),
	}
}

// activityExecutorClient implements ActivityExecutorClient.
type activityExecutorClient struct {
	execute *connect.Client[activity.ExecuteActivityRequest, activity.ExecuteActivityResponse]
}

// Execute calls activity.ActivityExecutor.Execute.
func (c *activityExecutorClient) Execute(ctx context.Context, req *connect.Request[activity.ExecuteActivityRequest]) (*connect.Response[activity.ExecuteActivityResponse], error) {
	return c.execute.CallUnary(ctx, req)
}

// ActivityExecutorHandler is an implementation of the activity.ActivityExecutor service.
type ActivityExecutorHandler interface {
	Execute(context.Context, *connect.Request[activity.ExecuteActivityRequest]) (*connect.Response[activity.ExecuteActivityResponse], error)
}

// NewActivityExecutorHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewActivityExecutorHandler(svc ActivityExecutorHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	activityExecutorMethods := activity.File_activity_activity_proto.Services().ByName("ActivityExecutor").Methods()
	activityExecutorExecuteHandler := connect.NewUnaryHandler(
		ActivityExecutorExecuteProcedure,
		svc.Execute,
		connect.WithSchema(activityExecutorMethods.ByName("Execute")),
		connect.WithHandlerOptions(opts...),
	)
	return "/activity.ActivityExecutor/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ActivityExecutorExecuteProcedure:
			activityExecutorExecuteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedActivityExecutorHandler returns CodeUnimplemented from all methods.
type UnimplementedActivityExecutorHandler struct{}

func (UnimplementedActivityExecutorHandler) Execute(context.Context, *connect.Request[activity.ExecuteActivityRequest]) (*connect.Response[activity.ExecuteActivityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("activity.ActivityExecutor.Execute is not implemented"))
}
