// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: activity/activity.proto

package activity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModuleRegistry_RegisterModule_FullMethodName   = "/activity.ModuleRegistry/RegisterModule"
	ModuleRegistry_UnregisterModule_FullMethodName = "/activity.ModuleRegistry/UnregisterModule"
	ModuleRegistry_ListModules_FullMethodName      = "/activity.ModuleRegistry/ListModules"
	ModuleRegistry_GetModule_FullMethodName        = "/activity.ModuleRegistry/GetModule"
	ModuleRegistry_ListActivities_FullMethodName   = "/activity.ModuleRegistry/ListActivities"
	ModuleRegistry_GetActivity_FullMethodName      = "/activity.ModuleRegistry/GetActivity"
)

// ModuleRegistryClient is the client API for ModuleRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModuleRegistryClient interface {
	RegisterModule(ctx context.Context, in *RegisterModuleRequest, opts ...grpc.CallOption) (*RegisterModuleResponse, error)
	UnregisterModule(ctx context.Context, in *UnregisterModuleRequest, opts ...grpc.CallOption) (*UnregisterModuleResponse, error)
	ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error)
	GetModule(ctx context.Context, in *GetModuleRequest, opts ...grpc.CallOption) (*GetModuleResponse, error)
	ListActivities(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error)
	GetActivity(ctx context.Context, in *GetActivityRequest, opts ...grpc.CallOption) (*GetActivityResponse, error)
}

type moduleRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewModuleRegistryClient(cc grpc.ClientConnInterface) ModuleRegistryClient {
	return &moduleRegistryClient{cc}
}

func (c *moduleRegistryClient) RegisterModule(ctx context.Context, in *RegisterModuleRequest, opts ...grpc.CallOption) (*RegisterModuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterModuleResponse)
	err := c.cc.Invoke(ctx, ModuleRegistry_RegisterModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleRegistryClient) UnregisterModule(ctx context.Context, in *UnregisterModuleRequest, opts ...grpc.CallOption) (*UnregisterModuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterModuleResponse)
	err := c.cc.Invoke(ctx, ModuleRegistry_UnregisterModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleRegistryClient) ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModulesResponse)
	err := c.cc.Invoke(ctx, ModuleRegistry_ListModules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleRegistryClient) GetModule(ctx context.Context, in *GetModuleRequest, opts ...grpc.CallOption) (*GetModuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModuleResponse)
	err := c.cc.Invoke(ctx, ModuleRegistry_GetModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleRegistryClient) ListActivities(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActivitiesResponse)
	err := c.cc.Invoke(ctx, ModuleRegistry_ListActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleRegistryClient) GetActivity(ctx context.Context, in *GetActivityRequest, opts ...grpc.CallOption) (*GetActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActivityResponse)
	err := c.cc.Invoke(ctx, ModuleRegistry_GetActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleRegistryServer is the server API for ModuleRegistry service.
// All implementations must embed UnimplementedModuleRegistryServer
// for forward compatibility.
type ModuleRegistryServer interface {
	RegisterModule(context.Context, *RegisterModuleRequest) (*RegisterModuleResponse, error)
	UnregisterModule(context.Context, *UnregisterModuleRequest) (*UnregisterModuleResponse, error)
	ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error)
	GetModule(context.Context, *GetModuleRequest) (*GetModuleResponse, error)
	ListActivities(context.Context, *ListActivitiesRequest) (*ListActivitiesResponse, error)
	GetActivity(context.Context, *GetActivityRequest) (*GetActivityResponse, error)
	mustEmbedUnimplementedModuleRegistryServer()
}

// UnimplementedModuleRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModuleRegistryServer struct{}

func (UnimplementedModuleRegistryServer) RegisterModule(context.Context, *RegisterModuleRequest) (*RegisterModuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterModule not implemented")
}
func (UnimplementedModuleRegistryServer) UnregisterModule(context.Context, *UnregisterModuleRequest) (*UnregisterModuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterModule not implemented")
}
func (UnimplementedModuleRegistryServer) ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModules not implemented")
}
func (UnimplementedModuleRegistryServer) GetModule(context.Context, *GetModuleRequest) (*GetModuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModule not implemented")
}
func (UnimplementedModuleRegistryServer) ListActivities(context.Context, *ListActivitiesRequest) (*ListActivitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActivities not implemented")
}
func (UnimplementedModuleRegistryServer) GetActivity(context.Context, *GetActivityRequest) (*GetActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActivity not implemented")
}
func (UnimplementedModuleRegistryServer) mustEmbedUnimplementedModuleRegistryServer() {}
func (UnimplementedModuleRegistryServer) testEmbeddedByValue()                        {}

// UnsafeModuleRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModuleRegistryServer will
// result in compilation errors.
type UnsafeModuleRegistryServer interface {
	mustEmbedUnimplementedModuleRegistryServer()
}

func RegisterModuleRegistryServer(s grpc.ServiceRegistrar, srv ModuleRegistryServer) {
	// If the following call panics, it indicates UnimplementedModuleRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModuleRegistry_ServiceDesc, srv)
}

func _ModuleRegistry_RegisterModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleRegistryServer).RegisterModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleRegistry_RegisterModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleRegistryServer).RegisterModule(ctx, req.(*RegisterModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleRegistry_UnregisterModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleRegistryServer).UnregisterModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleRegistry_UnregisterModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleRegistryServer).UnregisterModule(ctx, req.(*UnregisterModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleRegistry_ListModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleRegistryServer).ListModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleRegistry_ListModules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleRegistryServer).ListModules(ctx, req.(*ListModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleRegistry_GetModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleRegistryServer).GetModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleRegistry_GetModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleRegistryServer).GetModule(ctx, req.(*GetModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleRegistry_ListActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleRegistryServer).ListActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleRegistry_ListActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleRegistryServer).ListActivities(ctx, req.(*ListActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleRegistry_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleRegistryServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleRegistry_GetActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleRegistryServer).GetActivity(ctx, req.(*GetActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModuleRegistry_ServiceDesc is the grpc.ServiceDesc for ModuleRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModuleRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activity.ModuleRegistry",
	HandlerType: (*ModuleRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterModule",
			Handler:    _ModuleRegistry_RegisterModule_Handler,
		},
		{
			MethodName: "UnregisterModule",
			Handler:    _ModuleRegistry_UnregisterModule_Handler,
		},
		{
			MethodName: "ListModules",
			Handler:    _ModuleRegistry_ListModules_Handler,
		},
		{
			MethodName: "GetModule",
			Handler:    _ModuleRegistry_GetModule_Handler,
		},
		{
			MethodName: "ListActivities",
			Handler:    _ModuleRegistry_ListActivities_Handler,
		},
		{
			MethodName: "GetActivity",
			Handler:    _ModuleRegistry_GetActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity/activity.proto",
}

const (
	ActivityExecutor_Execute_FullMethodName = "/activity.ActivityExecutor/Execute"
)

// ActivityExecutorClient is the client API for ActivityExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityExecutorClient interface {
	Execute(ctx context.Context, in *ExecuteActivityRequest, opts ...grpc.CallOption) (*ExecuteActivityResponse, error)
}

type activityExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityExecutorClient(cc grpc.ClientConnInterface) ActivityExecutorClient {
	return &activityExecutorClient{cc}
}

func (c *activityExecutorClient) Execute(ctx context.Context, in *ExecuteActivityRequest, opts ...grpc.CallOption) (*ExecuteActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteActivityResponse)
	err := c.cc.Invoke(ctx, ActivityExecutor_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityExecutorServer is the server API for ActivityExecutor service.
// All implementations must embed UnimplementedActivityExecutorServer
// for forward compatibility.
type ActivityExecutorServer interface {
	Execute(context.Context, *ExecuteActivityRequest) (*ExecuteActivityResponse, error)
	mustEmbedUnimplementedActivityExecutorServer()
}

// UnimplementedActivityExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivityExecutorServer struct{}

func (UnimplementedActivityExecutorServer) Execute(context.Context, *ExecuteActivityRequest) (*ExecuteActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedActivityExecutorServer) mustEmbedUnimplementedActivityExecutorServer() {}
func (UnimplementedActivityExecutorServer) testEmbeddedByValue()                          {}

// UnsafeActivityExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityExecutorServer will
// result in compilation errors.
type UnsafeActivityExecutorServer interface {
	mustEmbedUnimplementedActivityExecutorServer()
}

func RegisterActivityExecutorServer(s grpc.ServiceRegistrar, srv ActivityExecutorServer) {
	// If the following call panics, it indicates UnimplementedActivityExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActivityExecutor_ServiceDesc, srv)
}

func _ActivityExecutor_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityExecutorServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityExecutor_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityExecutorServer).Execute(ctx, req.(*ExecuteActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivityExecutor_ServiceDesc is the grpc.ServiceDesc for ActivityExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivityExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activity.ActivityExecutor",
	HandlerType: (*ActivityExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _ActivityExecutor_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity/activity.proto",
}
