// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: activity/activity.proto

package activity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Metadata      *ModuleMetadata        `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Activities    []*ActivityDefinition  `protobuf:"bytes,6,rep,name=activities,proto3" json:"activities,omitempty"`
	TaskQueue     string                 `protobuf:"bytes,7,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_activity_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{0}
}

func (x *Module) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Module) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Module) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Module) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Module) GetMetadata() *ModuleMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Module) GetActivities() []*ActivityDefinition {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *Module) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

type ModuleMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Author           string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	DocumentationUrl string                 `protobuf:"bytes,2,opt,name=documentation_url,json=documentationUrl,proto3" json:"documentation_url,omitempty"`
	RepositoryUrl    string                 `protobuf:"bytes,3,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`
	Tags             []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Category         string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Labels           map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RegisteredAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModuleMetadata) Reset() {
	*x = ModuleMetadata{}
	mi := &file_activity_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleMetadata) ProtoMessage() {}

func (x *ModuleMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleMetadata.ProtoReflect.Descriptor instead.
func (*ModuleMetadata) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleMetadata) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ModuleMetadata) GetDocumentationUrl() string {
	if x != nil {
		return x.DocumentationUrl
	}
	return ""
}

func (x *ModuleMetadata) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *ModuleMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ModuleMetadata) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ModuleMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ModuleMetadata) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type ActivityDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	InputTypeUrl  string                 `protobuf:"bytes,4,opt,name=input_type_url,json=inputTypeUrl,proto3" json:"input_type_url,omitempty"`
	OutputTypeUrl string                 `protobuf:"bytes,5,opt,name=output_type_url,json=outputTypeUrl,proto3" json:"output_type_url,omitempty"`
	InputSchema   *anypb.Any             `protobuf:"bytes,6,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	OutputSchema  *anypb.Any             `protobuf:"bytes,7,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	SupportsAsync bool                   `protobuf:"varint,8,opt,name=supports_async,json=supportsAsync,proto3" json:"supports_async,omitempty"`
	TaskQueue     string                 `protobuf:"bytes,9,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	Metadata      *ActivityMetadata      `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityDefinition) Reset() {
	*x = ActivityDefinition{}
	mi := &file_activity_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityDefinition) ProtoMessage() {}

func (x *ActivityDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityDefinition.ProtoReflect.Descriptor instead.
func (*ActivityDefinition) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActivityDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActivityDefinition) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ActivityDefinition) GetInputTypeUrl() string {
	if x != nil {
		return x.InputTypeUrl
	}
	return ""
}

func (x *ActivityDefinition) GetOutputTypeUrl() string {
	if x != nil {
		return x.OutputTypeUrl
	}
	return ""
}

func (x *ActivityDefinition) GetInputSchema() *anypb.Any {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *ActivityDefinition) GetOutputSchema() *anypb.Any {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

func (x *ActivityDefinition) GetSupportsAsync() bool {
	if x != nil {
		return x.SupportsAsync
	}
	return false
}

func (x *ActivityDefinition) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *ActivityDefinition) GetMetadata() *ActivityMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ActivityMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DocumentationUrl string                 `protobuf:"bytes,1,opt,name=documentation_url,json=documentationUrl,proto3" json:"documentation_url,omitempty"`
	Tags             []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Category         string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Version          string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Labels           map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActivityMetadata) Reset() {
	*x = ActivityMetadata{}
	mi := &file_activity_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityMetadata) ProtoMessage() {}

func (x *ActivityMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityMetadata.ProtoReflect.Descriptor instead.
func (*ActivityMetadata) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{3}
}

func (x *ActivityMetadata) GetDocumentationUrl() string {
	if x != nil {
		return x.DocumentationUrl
	}
	return ""
}

func (x *ActivityMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ActivityMetadata) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ActivityMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ActivityMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type AsyncCallbackContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId      string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId           string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CallbackSignal  string                 `protobuf:"bytes,3,opt,name=callback_signal,json=callbackSignal,proto3" json:"callback_signal,omitempty"`
	CallbackTimeout string                 `protobuf:"bytes,4,opt,name=callback_timeout,json=callbackTimeout,proto3" json:"callback_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AsyncCallbackContext) Reset() {
	*x = AsyncCallbackContext{}
	mi := &file_activity_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncCallbackContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncCallbackContext) ProtoMessage() {}

func (x *AsyncCallbackContext) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncCallbackContext.ProtoReflect.Descriptor instead.
func (*AsyncCallbackContext) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{4}
}

func (x *AsyncCallbackContext) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *AsyncCallbackContext) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AsyncCallbackContext) GetCallbackSignal() string {
	if x != nil {
		return x.CallbackSignal
	}
	return ""
}

func (x *AsyncCallbackContext) GetCallbackTimeout() string {
	if x != nil {
		return x.CallbackTimeout
	}
	return ""
}

type RegisterModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModuleRequest) Reset() {
	*x = RegisterModuleRequest{}
	mi := &file_activity_activity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModuleRequest) ProtoMessage() {}

func (x *RegisterModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModuleRequest.ProtoReflect.Descriptor instead.
func (*RegisterModuleRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterModuleRequest) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

type RegisterModuleResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ModuleName           string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	RegisteredActivities []string               `protobuf:"bytes,2,rep,name=registered_activities,json=registeredActivities,proto3" json:"registered_activities,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterModuleResponse) Reset() {
	*x = RegisterModuleResponse{}
	mi := &file_activity_activity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModuleResponse) ProtoMessage() {}

func (x *RegisterModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModuleResponse.ProtoReflect.Descriptor instead.
func (*RegisterModuleResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterModuleResponse) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *RegisterModuleResponse) GetRegisteredActivities() []string {
	if x != nil {
		return x.RegisteredActivities
	}
	return nil
}

type UnregisterModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleName    string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterModuleRequest) Reset() {
	*x = UnregisterModuleRequest{}
	mi := &file_activity_activity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterModuleRequest) ProtoMessage() {}

func (x *UnregisterModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterModuleRequest.ProtoReflect.Descriptor instead.
func (*UnregisterModuleRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterModuleRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

type UnregisterModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterModuleResponse) Reset() {
	*x = UnregisterModuleResponse{}
	mi := &file_activity_activity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterModuleResponse) ProtoMessage() {}

func (x *UnregisterModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterModuleResponse.ProtoReflect.Descriptor instead.
func (*UnregisterModuleResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{8}
}

type ListModulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesRequest) Reset() {
	*x = ListModulesRequest{}
	mi := &file_activity_activity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesRequest) ProtoMessage() {}

func (x *ListModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesRequest.ProtoReflect.Descriptor instead.
func (*ListModulesRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{9}
}

type ListModulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*Module              `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesResponse) Reset() {
	*x = ListModulesResponse{}
	mi := &file_activity_activity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesResponse) ProtoMessage() {}

func (x *ListModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesResponse.ProtoReflect.Descriptor instead.
func (*ListModulesResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{10}
}

func (x *ListModulesResponse) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

type GetModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleName    string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleRequest) Reset() {
	*x = GetModuleRequest{}
	mi := &file_activity_activity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleRequest) ProtoMessage() {}

func (x *GetModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleRequest.ProtoReflect.Descriptor instead.
func (*GetModuleRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{11}
}

func (x *GetModuleRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

type GetModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleResponse) Reset() {
	*x = GetModuleResponse{}
	mi := &file_activity_activity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleResponse) ProtoMessage() {}

func (x *GetModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleResponse.ProtoReflect.Descriptor instead.
func (*GetModuleResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{12}
}

func (x *GetModuleResponse) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

type ListActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleName    string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesRequest) Reset() {
	*x = ListActivitiesRequest{}
	mi := &file_activity_activity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesRequest) ProtoMessage() {}

func (x *ListActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesRequest.ProtoReflect.Descriptor instead.
func (*ListActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{13}
}

func (x *ListActivitiesRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ListActivitiesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*ActivityDefinition  `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesResponse) Reset() {
	*x = ListActivitiesResponse{}
	mi := &file_activity_activity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesResponse) ProtoMessage() {}

func (x *ListActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesResponse.ProtoReflect.Descriptor instead.
func (*ListActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{14}
}

func (x *ListActivitiesResponse) GetActivities() []*ActivityDefinition {
	if x != nil {
		return x.Activities
	}
	return nil
}

type GetActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleName    string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	ActivityName  string                 `protobuf:"bytes,2,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityRequest) Reset() {
	*x = GetActivityRequest{}
	mi := &file_activity_activity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityRequest) ProtoMessage() {}

func (x *GetActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityRequest.ProtoReflect.Descriptor instead.
func (*GetActivityRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{15}
}

func (x *GetActivityRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *GetActivityRequest) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

type GetActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *ActivityDefinition    `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	ModuleName    string                 `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityResponse) Reset() {
	*x = GetActivityResponse{}
	mi := &file_activity_activity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityResponse) ProtoMessage() {}

func (x *GetActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityResponse.ProtoReflect.Descriptor instead.
func (*GetActivityResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{16}
}

func (x *GetActivityResponse) GetActivity() *ActivityDefinition {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *GetActivityResponse) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

type ExecuteActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleName    string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	ActivityName  string                 `protobuf:"bytes,2,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`
	Input         *anypb.Any             `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AsyncContext  *AsyncCallbackContext  `protobuf:"bytes,5,opt,name=async_context,json=asyncContext,proto3" json:"async_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActivityRequest) Reset() {
	*x = ExecuteActivityRequest{}
	mi := &file_activity_activity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActivityRequest) ProtoMessage() {}

func (x *ExecuteActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActivityRequest.ProtoReflect.Descriptor instead.
func (*ExecuteActivityRequest) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{17}
}

func (x *ExecuteActivityRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ExecuteActivityRequest) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *ExecuteActivityRequest) GetInput() *anypb.Any {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteActivityRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteActivityRequest) GetAsyncContext() *AsyncCallbackContext {
	if x != nil {
		return x.AsyncContext
	}
	return nil
}

type ExecuteActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *anypb.Any             `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActivityResponse) Reset() {
	*x = ExecuteActivityResponse{}
	mi := &file_activity_activity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActivityResponse) ProtoMessage() {}

func (x *ExecuteActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_activity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActivityResponse.ProtoReflect.Descriptor instead.
func (*ExecuteActivityResponse) Descriptor() ([]byte, []int) {
	return file_activity_activity_proto_rawDescGZIP(), []int{18}
}

func (x *ExecuteActivityResponse) GetOutput() *anypb.Any {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteActivityResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_activity_activity_proto protoreflect.FileDescriptor

const file_activity_activity_proto_rawDesc = "" +
	"\n" +
	"\x17activity/activity.proto\x12\bactivity\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x01\n" +
	"\x06Module\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x124\n" +
	"\bmetadata\x18\x05 \x01(\v2\x18.activity.ModuleMetadataR\bmetadata\x12<\n" +
	"\n" +
	"activities\x18\x06 \x03(\v2\x1c.activity.ActivityDefinitionR\n" +
	"activities\x12\x1d\n" +
	"\n" +
	"task_queue\x18\a \x01(\tR\ttaskQueue\"\xe6\x02\n" +
	"\x0eModuleMetadata\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12+\n" +
	"\x11documentation_url\x18\x02 \x01(\tR\x10documentationUrl\x12%\n" +
	"\x0erepository_url\x18\x03 \x01(\tR\rrepositoryUrl\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12<\n" +
	"\x06labels\x18\x06 \x03(\v2$.activity.ModuleMetadata.LabelsEntryR\x06labels\x12?\n" +
	"\rregistered_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x03\n" +
	"\x12ActivityDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12$\n" +
	"\x0einput_type_url\x18\x04 \x01(\tR\finputTypeUrl\x12&\n" +
	"\x0foutput_type_url\x18\x05 \x01(\tR\routputTypeUrl\x127\n" +
	"\finput_schema\x18\x06 \x01(\v2\x14.google.protobuf.AnyR\vinputSchema\x129\n" +
	"\routput_schema\x18\a \x01(\v2\x14.google.protobuf.AnyR\foutputSchema\x12%\n" +
	"\x0esupports_async\x18\b \x01(\bR\rsupportsAsync\x12\x1d\n" +
	"\n" +
	"task_queue\x18\t \x01(\tR\ttaskQueue\x126\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1a.activity.ActivityMetadataR\bmetadata\"\x84\x02\n" +
	"\x10ActivityMetadata\x12+\n" +
	"\x11documentation_url\x18\x01 \x01(\tR\x10documentationUrl\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12>\n" +
	"\x06labels\x18\x05 \x03(\v2&.activity.ActivityMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x01\n" +
	"\x14AsyncCallbackContext\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12'\n" +
	"\x0fcallback_signal\x18\x03 \x01(\tR\x0ecallbackSignal\x12)\n" +
	"\x10callback_timeout\x18\x04 \x01(\tR\x0fcallbackTimeout\"A\n" +
	"\x15RegisterModuleRequest\x12(\n" +
	"\x06module\x18\x01 \x01(\v2\x10.activity.ModuleR\x06module\"n\n" +
	"\x16RegisterModuleResponse\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\x123\n" +
	"\x15registered_activities\x18\x02 \x03(\tR\x14registeredActivities\":\n" +
	"\x17UnregisterModuleRequest\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\"\x1a\n" +
	"\x18UnregisterModuleResponse\"\x14\n" +
	"\x12ListModulesRequest\"A\n" +
	"\x13ListModulesResponse\x12*\n" +
	"\amodules\x18\x01 \x03(\v2\x10.activity.ModuleR\amodules\"3\n" +
	"\x10GetModuleRequest\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\"=\n" +
	"\x11GetModuleResponse\x12(\n" +
	"\x06module\x18\x01 \x01(\v2\x10.activity.ModuleR\x06module\"T\n" +
	"\x15ListActivitiesRequest\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"V\n" +
	"\x16ListActivitiesResponse\x12<\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x1c.activity.ActivityDefinitionR\n" +
	"activities\"Z\n" +
	"\x12GetActivityRequest\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\x12#\n" +
	"\ractivity_name\x18\x02 \x01(\tR\factivityName\"p\n" +
	"\x13GetActivityResponse\x128\n" +
	"\bactivity\x18\x01 \x01(\v2\x1c.activity.ActivityDefinitionR\bactivity\x12\x1f\n" +
	"\vmodule_name\x18\x02 \x01(\tR\n" +
	"moduleName\"\xd8\x02\n" +
	"\x16ExecuteActivityRequest\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\x12#\n" +
	"\ractivity_name\x18\x02 \x01(\tR\factivityName\x12*\n" +
	"\x05input\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x05input\x12J\n" +
	"\bmetadata\x18\x04 \x03(\v2..activity.ExecuteActivityRequest.MetadataEntryR\bmetadata\x12C\n" +
	"\rasync_context\x18\x05 \x01(\v2\x1e.activity.AsyncCallbackContextR\fasyncContext\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x17ExecuteActivityResponse\x12,\n" +
	"\x06output\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xf3\x03\n" +
	"\x0eModuleRegistry\x12S\n" +
	"\x0eRegisterModule\x12\x1f.activity.RegisterModuleRequest\x1a .activity.RegisterModuleResponse\x12Y\n" +
	"\x10UnregisterModule\x12!.activity.UnregisterModuleRequest\x1a\".activity.UnregisterModuleResponse\x12J\n" +
	"\vListModules\x12\x1c.activity.ListModulesRequest\x1a\x1d.activity.ListModulesResponse\x12D\n" +
	"\tGetModule\x12\x1a.activity.GetModuleRequest\x1a\x1b.activity.GetModuleResponse\x12S\n" +
	"\x0eListActivities\x12\x1f.activity.ListActivitiesRequest\x1a .activity.ListActivitiesResponse\x12J\n" +
	"\vGetActivity\x12\x1c.activity.GetActivityRequest\x1a\x1d.activity.GetActivityResponse2b\n" +
	"\x10ActivityExecutor\x12N\n" +
	"\aExecute\x12 .activity.ExecuteActivityRequest\x1a!.activity.ExecuteActivityResponseB>Z<github.com/mas-soft/masflow/sdk/internal/activitypb/activityb\x06proto3"

var (
	file_activity_activity_proto_rawDescOnce sync.Once
	file_activity_activity_proto_rawDescData []byte
)

func file_activity_activity_proto_rawDescGZIP() []byte {
	file_activity_activity_proto_rawDescOnce.Do(func() {
		file_activity_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_activity_proto_rawDesc), len(file_activity_activity_proto_rawDesc)))
	})
	return file_activity_activity_proto_rawDescData
}

var file_activity_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_activity_activity_proto_goTypes = []any{
	(*Module)(nil),                   // 0: activity.Module
	(*ModuleMetadata)(nil),           // 1: activity.ModuleMetadata
	(*ActivityDefinition)(nil),       // 2: activity.ActivityDefinition
	(*ActivityMetadata)(nil),         // 3: activity.ActivityMetadata
	(*AsyncCallbackContext)(nil),     // 4: activity.AsyncCallbackContext
	(*RegisterModuleRequest)(nil),    // 5: activity.RegisterModuleRequest
	(*RegisterModuleResponse)(nil),   // 6: activity.RegisterModuleResponse
	(*UnregisterModuleRequest)(nil),  // 7: activity.UnregisterModuleRequest
	(*UnregisterModuleResponse)(nil), // 8: activity.UnregisterModuleResponse
	(*ListModulesRequest)(nil),       // 9: activity.ListModulesRequest
	(*ListModulesResponse)(nil),      // 10: activity.ListModulesResponse
	(*GetModuleRequest)(nil),         // 11: activity.GetModuleRequest
	(*GetModuleResponse)(nil),        // 12: activity.GetModuleResponse
	(*ListActivitiesRequest)(nil),    // 13: activity.ListActivitiesRequest
	(*ListActivitiesResponse)(nil),   // 14: activity.ListActivitiesResponse
	(*GetActivityRequest)(nil),       // 15: activity.GetActivityRequest
	(*GetActivityResponse)(nil),      // 16: activity.GetActivityResponse
	(*ExecuteActivityRequest)(nil),   // 17: activity.ExecuteActivityRequest
	(*ExecuteActivityResponse)(nil),  // 18: activity.ExecuteActivityResponse
	nil,                              // 19: activity.ModuleMetadata.LabelsEntry
	nil,                              // 20: activity.ActivityMetadata.LabelsEntry
	nil,                              // 21: activity.ExecuteActivityRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 22: google.protobuf.Timestamp
	(*anypb.Any)(nil),                // 23: google.protobuf.Any
}
var file_activity_activity_proto_depIdxs = []int32{
	1,  // 0: activity.Module.metadata:type_name -> activity.ModuleMetadata
	2,  // 1: activity.Module.activities:type_name -> activity.ActivityDefinition
	19, // 2: activity.ModuleMetadata.labels:type_name -> activity.ModuleMetadata.LabelsEntry
	22, // 3: activity.ModuleMetadata.registered_at:type_name -> google.protobuf.Timestamp
	23, // 4: activity.ActivityDefinition.input_schema:type_name -> google.protobuf.Any
	23, // 5: activity.ActivityDefinition.output_schema:type_name -> google.protobuf.Any
	3,  // 6: activity.ActivityDefinition.metadata:type_name -> activity.ActivityMetadata
	20, // 7: activity.ActivityMetadata.labels:type_name -> activity.ActivityMetadata.LabelsEntry
	0,  // 8: activity.RegisterModuleRequest.module:type_name -> activity.Module
	0,  // 9: activity.ListModulesResponse.modules:type_name -> activity.Module
	0,  // 10: activity.GetModuleResponse.module:type_name -> activity.Module
	2,  // 11: activity.ListActivitiesResponse.activities:type_name -> activity.ActivityDefinition
	2,  // 12: activity.GetActivityResponse.activity:type_name -> activity.ActivityDefinition
	23, // 13: activity.ExecuteActivityRequest.input:type_name -> google.protobuf.Any
	21, // 14: activity.ExecuteActivityRequest.metadata:type_name -> activity.ExecuteActivityRequest.MetadataEntry
	4,  // 15: activity.ExecuteActivityRequest.async_context:type_name -> activity.AsyncCallbackContext
	23, // 16: activity.ExecuteActivityResponse.output:type_name -> google.protobuf.Any
	5,  // 17: activity.ModuleRegistry.RegisterModule:input_type -> activity.RegisterModuleRequest
	7,  // 18: activity.ModuleRegistry.UnregisterModule:input_type -> activity.UnregisterModuleRequest
	9,  // 19: activity.ModuleRegistry.ListModules:input_type -> activity.ListModulesRequest
	11, // 20: activity.ModuleRegistry.GetModule:input_type -> activity.GetModuleRequest
	13, // 21: activity.ModuleRegistry.ListActivities:input_type -> activity.ListActivitiesRequest
	15, // 22: activity.ModuleRegistry.GetActivity:input_type -> activity.GetActivityRequest
	17, // 23: activity.ActivityExecutor.Execute:input_type -> activity.ExecuteActivityRequest
	6,  // 24: activity.ModuleRegistry.RegisterModule:output_type -> activity.RegisterModuleResponse
	8,  // 25: activity.ModuleRegistry.UnregisterModule:output_type -> activity.UnregisterModuleResponse
	10, // 26: activity.ModuleRegistry.ListModules:output_type -> activity.ListModulesResponse
	12, // 27: activity.ModuleRegistry.GetModule:output_type -> activity.GetModuleResponse
	14, // 28: activity.ModuleRegistry.ListActivities:output_type -> activity.ListActivitiesResponse
	16, // 29: activity.ModuleRegistry.GetActivity:output_type -> activity.GetActivityResponse
	18, // 30: activity.ActivityExecutor.Execute:output_type -> activity.ExecuteActivityResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_activity_activity_proto_init() }
func file_activity_activity_proto_init() {
	if File_activity_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_activity_proto_rawDesc), len(file_activity_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_activity_activity_proto_goTypes,
		DependencyIndexes: file_activity_activity_proto_depIdxs,
		MessageInfos:      file_activity_activity_proto_msgTypes,
	}.Build()
	File_activity_activity_proto = out.File
	file_activity_activity_proto_goTypes = nil
	file_activity_activity_proto_depIdxs = nil
}
