// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: workflow/workflow.proto

package workflowconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	workflow "github.com/mas-soft/masflow/sdk/internal/pb/workflow"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkflowServiceName is the fully-qualified name of the WorkflowService service.
	WorkflowServiceName = "workflow.WorkflowService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkflowServiceExecuteWorkflowSourceProcedure is the fully-qualified name of the
	// WorkflowService's ExecuteWorkflowSource RPC.
	WorkflowServiceExecuteWorkflowSourceProcedure = "/workflow.WorkflowService/ExecuteWorkflowSource"
	// WorkflowServiceExecuteWorkflowDeclarationProcedure is the fully-qualified name of the
	// WorkflowService's ExecuteWorkflowDeclaration RPC.
	WorkflowServiceExecuteWorkflowDeclarationProcedure = "/workflow.WorkflowService/ExecuteWorkflowDeclaration"
	// WorkflowServiceGetWorkflowStatusProcedure is the fully-qualified name of the WorkflowService's
	// GetWorkflowStatus RPC.
	WorkflowServiceGetWorkflowStatusProcedure = "/workflow.WorkflowService/GetWorkflowStatus"
	// WorkflowServiceDescribeWorkflowProcedure is the fully-qualified name of the WorkflowService's
	// DescribeWorkflow RPC.
	WorkflowServiceDescribeWorkflowProcedure = "/workflow.WorkflowService/DescribeWorkflow"
	// WorkflowServiceListWorkflowsProcedure is the fully-qualified name of the WorkflowService's
	// ListWorkflows RPC.
	WorkflowServiceListWorkflowsProcedure = "/workflow.WorkflowService/ListWorkflows"
	// WorkflowServiceQueryWorkflowProcedure is the fully-qualified name of the WorkflowService's
	// QueryWorkflow RPC.
	WorkflowServiceQueryWorkflowProcedure = "/workflow.WorkflowService/QueryWorkflow"
	// WorkflowServiceQueryMonitorStatusProcedure is the fully-qualified name of the WorkflowService's
	// QueryMonitorStatus RPC.
	WorkflowServiceQueryMonitorStatusProcedure = "/workflow.WorkflowService/QueryMonitorStatus"
	// WorkflowServiceQueryTraceProcedure is the fully-qualified name of the WorkflowService's
	// QueryTrace RPC.
	WorkflowServiceQueryTraceProcedure = "/workflow.WorkflowService/QueryTrace"
	// WorkflowServiceCancelWorkflowProcedure is the fully-qualified name of the WorkflowService's
	// CancelWorkflow RPC.
	WorkflowServiceCancelWorkflowProcedure = "/workflow.WorkflowService/CancelWorkflow"
	// WorkflowServiceSignalWorkflowProcedure is the fully-qualified name of the WorkflowService's
	// SignalWorkflow RPC.
	WorkflowServiceSignalWorkflowProcedure = "/workflow.WorkflowService/SignalWorkflow"
	// WorkflowServiceTerminateWorkflowProcedure is the fully-qualified name of the WorkflowService's
	// TerminateWorkflow RPC.
	WorkflowServiceTerminateWorkflowProcedure = "/workflow.WorkflowService/TerminateWorkflow"
	// WorkflowServicePauseWorkflowProcedure is the fully-qualified name of the WorkflowService's
	// PauseWorkflow RPC.
	WorkflowServicePauseWorkflowProcedure = "/workflow.WorkflowService/PauseWorkflow"
	// WorkflowServiceResumeWorkflowProcedure is the fully-qualified name of the WorkflowService's
	// ResumeWorkflow RPC.
	WorkflowServiceResumeWorkflowProcedure = "/workflow.WorkflowService/ResumeWorkflow"
	// WorkflowServiceSearchWorkflowsProcedure is the fully-qualified name of the WorkflowService's
	// SearchWorkflows RPC.
	WorkflowServiceSearchWorkflowsProcedure = "/workflow.WorkflowService/SearchWorkflows"
	// WorkflowServiceValidateWorkflowProcedure is the fully-qualified name of the WorkflowService's
	// ValidateWorkflow RPC.
	WorkflowServiceValidateWorkflowProcedure = "/workflow.WorkflowService/ValidateWorkflow"
)

// WorkflowServiceClient is a client for the workflow.WorkflowService service.
type WorkflowServiceClient interface {
	ExecuteWorkflowSource(context.Context, *connect.Request[workflow.ExecuteWorkflowSourceRequest]) (*connect.Response[workflow.ExecuteWorkflowResponse], error)
	ExecuteWorkflowDeclaration(context.Context, *connect.Request[workflow.ExecuteWorkflowDeclarationRequest]) (*connect.Response[workflow.ExecuteWorkflowDeclarationResponse], error)
	GetWorkflowStatus(context.Context, *connect.Request[workflow.GetWorkflowStatusRequest]) (*connect.Response[workflow.GetWorkflowStatusResponse], error)
	DescribeWorkflow(context.Context, *connect.Request[workflow.DescribeWorkflowRequest]) (*connect.Response[workflow.DescribeWorkflowResponse], error)
	ListWorkflows(context.Context, *connect.Request[workflow.ListWorkflowsRequest]) (*connect.Response[workflow.ListWorkflowsResponse], error)
	QueryWorkflow(context.Context, *connect.Request[workflow.QueryWorkflowRequest]) (*connect.Response[workflow.QueryWorkflowResponse], error)
	QueryMonitorStatus(context.Context, *connect.Request[workflow.QueryMonitorStatusRequest]) (*connect.Response[workflow.QueryMonitorStatusResponse], error)
	QueryTrace(context.Context, *connect.Request[workflow.QueryTraceRequest]) (*connect.Response[workflow.QueryTraceResponse], error)
	CancelWorkflow(context.Context, *connect.Request[workflow.CancelWorkflowRequest]) (*connect.Response[workflow.CancelWorkflowResponse], error)
	SignalWorkflow(context.Context, *connect.Request[workflow.SignalWorkflowRequest]) (*connect.Response[workflow.SignalWorkflowResponse], error)
	TerminateWorkflow(context.Context, *connect.Request[workflow.TerminateWorkflowRequest]) (*connect.Response[workflow.TerminateWorkflowResponse], error)
	PauseWorkflow(context.Context, *connect.Request[workflow.PauseWorkflowRequest]) (*connect.Response[workflow.PauseWorkflowResponse], error)
	ResumeWorkflow(context.Context, *connect.Request[workflow.ResumeWorkflowRequest]) (*connect.Response[workflow.ResumeWorkflowResponse], error)
	SearchWorkflows(context.Context, *connect.Request[workflow.SearchWorkflowsRequest]) (*connect.Response[workflow.SearchWorkflowsResponse], error)
	ValidateWorkflow(context.Context, *connect.Request[workflow.ValidateWorkflowRequest]) (*connect.Response[workflow.ValidateWorkflowResponse], error)
}

// NewWorkflowServiceClient constructs a client for the workflow.WorkflowService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkflowServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkflowServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workflowServiceMethods := workflow.File_workflow_workflow_proto.Services().ByName("WorkflowService").Methods()
	return &workflowServiceClient{
		executeWorkflowSource: connect.NewClient[workflow.ExecuteWorkflowSourceRequest, workflow.ExecuteWorkflowResponse](
			httpClient,
			baseURL+WorkflowServiceExecuteWorkflowSourceProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("ExecuteWorkflowSource")),
			connect.WithClientOptions(opts...),
		),
		executeWorkflowDeclaration: connect.NewClient[workflow.ExecuteWorkflowDeclarationRequest, workflow.ExecuteWorkflowDeclarationResponse](
			httpClient,
			baseURL+WorkflowServiceExecuteWorkflowDeclarationProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("ExecuteWorkflowDeclaration")),
			connect.WithClientOptions(opts...),
		),
		getWorkflowStatus: connect.NewClient[workflow.GetWorkflowStatusRequest, workflow.GetWorkflowStatusResponse](
			httpClient,
			baseURL+WorkflowServiceGetWorkflowStatusProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("GetWorkflowStatus")),
			connect.WithClientOptions(opts...),
		),
		describeWorkflow: connect.NewClient[workflow.DescribeWorkflowRequest, workflow.DescribeWorkflowResponse](
			httpClient,
			baseURL+WorkflowServiceDescribeWorkflowProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("DescribeWorkflow")),
			connect.WithClientOptions(opts...),
		),
		listWorkflows: connect.NewClient[workflow.ListWorkflowsRequest, workflow.ListWorkflowsResponse](
			httpClient,
			baseURL+WorkflowServiceListWorkflowsProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("ListWorkflows")),
			connect.WithClientOptions(opts...),
		),
		queryWorkflow: connect.NewClient[workflow.QueryWorkflowRequest, workflow.QueryWorkflowResponse](
			httpClient,
			baseURL+WorkflowServiceQueryWorkflowProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("QueryWorkflow")),
			connect.WithClientOptions(opts...),
		),
		queryMonitorStatus: connect.NewClient[workflow.QueryMonitorStatusRequest, workflow.QueryMonitorStatusResponse](
			httpClient,
			baseURL+WorkflowServiceQueryMonitorStatusProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("QueryMonitorStatus")),
			connect.WithClientOptions(opts...),
		),
		queryTrace: connect.NewClient[workflow.QueryTraceRequest, workflow.QueryTraceResponse](
			httpClient,
			baseURL+WorkflowServiceQueryTraceProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("QueryTrace")),
			connect.WithClientOptions(opts...),
		),
		cancelWorkflow: connect.NewClient[workflow.CancelWorkflowRequest, workflow.CancelWorkflowResponse](
			httpClient,
			baseURL+WorkflowServiceCancelWorkflowProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("CancelWorkflow")),
			connect.WithClientOptions(opts...),
		),
		signalWorkflow: connect.NewClient[workflow.SignalWorkflowRequest, workflow.SignalWorkflowResponse](
			httpClient,
			baseURL+WorkflowServiceSignalWorkflowProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("SignalWorkflow")),
			connect.WithClientOptions(opts...),
		),
		terminateWorkflow: connect.NewClient[workflow.TerminateWorkflowRequest, workflow.TerminateWorkflowResponse](
			httpClient,
			baseURL+WorkflowServiceTerminateWorkflowProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("TerminateWorkflow")),
			connect.WithClientOptions(opts...),
		),
		pauseWorkflow: connect.NewClient[workflow.PauseWorkflowRequest, workflow.PauseWorkflowResponse](
			httpClient,
			baseURL+WorkflowServicePauseWorkflowProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("PauseWorkflow")),
			connect.WithClientOptions(opts...),
		),
		resumeWorkflow: connect.NewClient[workflow.ResumeWorkflowRequest, workflow.ResumeWorkflowResponse](
			httpClient,
			baseURL+WorkflowServiceResumeWorkflowProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("ResumeWorkflow")),
			connect.WithClientOptions(opts...),
		),
		searchWorkflows: connect.NewClient[workflow.SearchWorkflowsRequest, workflow.SearchWorkflowsResponse](
			httpClient,
			baseURL+WorkflowServiceSearchWorkflowsProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("SearchWorkflows")),
			connect.WithClientOptions(opts...),
		),
		validateWorkflow: connect.NewClient[workflow.ValidateWorkflowRequest, workflow.ValidateWorkflowResponse](
			httpClient,
			baseURL+WorkflowServiceValidateWorkflowProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("ValidateWorkflow")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workflowServiceClient implements WorkflowServiceClient.
type workflowServiceClient struct {
	executeWorkflowSource      *connect.Client[workflow.ExecuteWorkflowSourceRequest, workflow.ExecuteWorkflowResponse]
	executeWorkflowDeclaration *connect.Client[workflow.ExecuteWorkflowDeclarationRequest, workflow.ExecuteWorkflowDeclarationResponse]
	getWorkflowStatus          *connect.Client[workflow.GetWorkflowStatusRequest, workflow.GetWorkflowStatusResponse]
	describeWorkflow           *connect.Client[workflow.DescribeWorkflowRequest, workflow.DescribeWorkflowResponse]
	listWorkflows              *connect.Client[workflow.ListWorkflowsRequest, workflow.ListWorkflowsResponse]
	queryWorkflow              *connect.Client[workflow.QueryWorkflowRequest, workflow.QueryWorkflowResponse]
	queryMonitorStatus         *connect.Client[workflow.QueryMonitorStatusRequest, workflow.QueryMonitorStatusResponse]
	queryTrace                 *connect.Client[workflow.QueryTraceRequest, workflow.QueryTraceResponse]
	cancelWorkflow             *connect.Client[workflow.CancelWorkflowRequest, workflow.CancelWorkflowResponse]
	signalWorkflow             *connect.Client[workflow.SignalWorkflowRequest, workflow.SignalWorkflowResponse]
	terminateWorkflow          *connect.Client[workflow.TerminateWorkflowRequest, workflow.TerminateWorkflowResponse]
	pauseWorkflow              *connect.Client[workflow.PauseWorkflowRequest, workflow.PauseWorkflowResponse]
	resumeWorkflow             *connect.Client[workflow.ResumeWorkflowRequest, workflow.ResumeWorkflowResponse]
	searchWorkflows            *connect.Client[workflow.SearchWorkflowsRequest, workflow.SearchWorkflowsResponse]
	validateWorkflow           *connect.Client[workflow.ValidateWorkflowRequest, workflow.ValidateWorkflowResponse]
}

// ExecuteWorkflowSource calls workflow.WorkflowService.ExecuteWorkflowSource.
func (c *workflowServiceClient) ExecuteWorkflowSource(ctx context.Context, req *connect.Request[workflow.ExecuteWorkflowSourceRequest]) (*connect.Response[workflow.ExecuteWorkflowResponse], error) {
	return c.executeWorkflowSource.CallUnary(ctx, req)
}

// ExecuteWorkflowDeclaration calls workflow.WorkflowService.ExecuteWorkflowDeclaration.
func (c *workflowServiceClient) ExecuteWorkflowDeclaration(ctx context.Context, req *connect.Request[workflow.ExecuteWorkflowDeclarationRequest]) (*connect.Response[workflow.ExecuteWorkflowDeclarationResponse], error) {
	return c.executeWorkflowDeclaration.CallUnary(ctx, req)
}

// GetWorkflowStatus calls workflow.WorkflowService.GetWorkflowStatus.
func (c *workflowServiceClient) GetWorkflowStatus(ctx context.Context, req *connect.Request[workflow.GetWorkflowStatusRequest]) (*connect.Response[workflow.GetWorkflowStatusResponse], error) {
	return c.getWorkflowStatus.CallUnary(ctx, req)
}

// DescribeWorkflow calls workflow.WorkflowService.DescribeWorkflow.
func (c *workflowServiceClient) DescribeWorkflow(ctx context.Context, req *connect.Request[workflow.DescribeWorkflowRequest]) (*connect.Response[workflow.DescribeWorkflowResponse], error) {
	return c.describeWorkflow.CallUnary(ctx, req)
}

// ListWorkflows calls workflow.WorkflowService.ListWorkflows.
func (c *workflowServiceClient) ListWorkflows(ctx context.Context, req *connect.Request[workflow.ListWorkflowsRequest]) (*connect.Response[workflow.ListWorkflowsResponse], error) {
	return c.listWorkflows.CallUnary(ctx, req)
}

// QueryWorkflow calls workflow.WorkflowService.QueryWorkflow.
func (c *workflowServiceClient) QueryWorkflow(ctx context.Context, req *connect.Request[workflow.QueryWorkflowRequest]) (*connect.Response[workflow.QueryWorkflowResponse], error) {
	return c.queryWorkflow.CallUnary(ctx, req)
}

// QueryMonitorStatus calls workflow.WorkflowService.QueryMonitorStatus.
func (c *workflowServiceClient) QueryMonitorStatus(ctx context.Context, req *connect.Request[workflow.QueryMonitorStatusRequest]) (*connect.Response[workflow.QueryMonitorStatusResponse], error) {
	return c.queryMonitorStatus.CallUnary(ctx, req)
}

// QueryTrace calls workflow.WorkflowService.QueryTrace.
func (c *workflowServiceClient) QueryTrace(ctx context.Context, req *connect.Request[workflow.QueryTraceRequest]) (*connect.Response[workflow.QueryTraceResponse], error) {
	return c.queryTrace.CallUnary(ctx, req)
}

// CancelWorkflow calls workflow.WorkflowService.CancelWorkflow.
func (c *workflowServiceClient) CancelWorkflow(ctx context.Context, req *connect.Request[workflow.CancelWorkflowRequest]) (*connect.Response[workflow.CancelWorkflowResponse], error) {
	return c.cancelWorkflow.CallUnary(ctx, req)
}

// SignalWorkflow calls workflow.WorkflowService.SignalWorkflow.
func (c *workflowServiceClient) SignalWorkflow(ctx context.Context, req *connect.Request[workflow.SignalWorkflowRequest]) (*connect.Response[workflow.SignalWorkflowResponse], error) {
	return c.signalWorkflow.CallUnary(ctx, req)
}

// TerminateWorkflow calls workflow.WorkflowService.TerminateWorkflow.
func (c *workflowServiceClient) TerminateWorkflow(ctx context.Context, req *connect.Request[workflow.TerminateWorkflowRequest]) (*connect.Response[workflow.TerminateWorkflowResponse], error) {
	return c.terminateWorkflow.CallUnary(ctx, req)
}

// PauseWorkflow calls workflow.WorkflowService.PauseWorkflow.
func (c *workflowServiceClient) PauseWorkflow(ctx context.Context, req *connect.Request[workflow.PauseWorkflowRequest]) (*connect.Response[workflow.PauseWorkflowResponse], error) {
	return c.pauseWorkflow.CallUnary(ctx, req)
}

// ResumeWorkflow calls workflow.WorkflowService.ResumeWorkflow.
func (c *workflowServiceClient) ResumeWorkflow(ctx context.Context, req *connect.Request[workflow.ResumeWorkflowRequest]) (*connect.Response[workflow.ResumeWorkflowResponse], error) {
	return c.resumeWorkflow.CallUnary(ctx, req)
}

// SearchWorkflows calls workflow.WorkflowService.SearchWorkflows.
func (c *workflowServiceClient) SearchWorkflows(ctx context.Context, req *connect.Request[workflow.SearchWorkflowsRequest]) (*connect.Response[workflow.SearchWorkflowsResponse], error) {
	return c.searchWorkflows.CallUnary(ctx, req)
}

// ValidateWorkflow calls workflow.WorkflowService.ValidateWorkflow.
func (c *workflowServiceClient) ValidateWorkflow(ctx context.Context, req *connect.Request[workflow.ValidateWorkflowRequest]) (*connect.Response[workflow.ValidateWorkflowResponse], error) {
	return c.validateWorkflow.CallUnary(ctx, req)
}

// WorkflowServiceHandler is an implementation of the workflow.WorkflowService service.
type WorkflowServiceHandler interface {
	ExecuteWorkflowSource(context.Context, *connect.Request[workflow.ExecuteWorkflowSourceRequest]) (*connect.Response[workflow.ExecuteWorkflowResponse], error)
	ExecuteWorkflowDeclaration(context.Context, *connect.Request[workflow.ExecuteWorkflowDeclarationRequest]) (*connect.Response[workflow.ExecuteWorkflowDeclarationResponse], error)
	GetWorkflowStatus(context.Context, *connect.Request[workflow.GetWorkflowStatusRequest]) (*connect.Response[workflow.GetWorkflowStatusResponse], error)
	DescribeWorkflow(context.Context, *connect.Request[workflow.DescribeWorkflowRequest]) (*connect.Response[workflow.DescribeWorkflowResponse], error)
	ListWorkflows(context.Context, *connect.Request[workflow.ListWorkflowsRequest]) (*connect.Response[workflow.ListWorkflowsResponse], error)
	QueryWorkflow(context.Context, *connect.Request[workflow.QueryWorkflowRequest]) (*connect.Response[workflow.QueryWorkflowResponse], error)
	QueryMonitorStatus(context.Context, *connect.Request[workflow.QueryMonitorStatusRequest]) (*connect.Response[workflow.QueryMonitorStatusResponse], error)
	QueryTrace(context.Context, *connect.Request[workflow.QueryTraceRequest]) (*connect.Response[workflow.QueryTraceResponse], error)
	CancelWorkflow(context.Context, *connect.Request[workflow.CancelWorkflowRequest]) (*connect.Response[workflow.CancelWorkflowResponse], error)
	SignalWorkflow(context.Context, *connect.Request[workflow.SignalWorkflowRequest]) (*connect.Response[workflow.SignalWorkflowResponse], error)
	TerminateWorkflow(context.Context, *connect.Request[workflow.TerminateWorkflowRequest]) (*connect.Response[workflow.TerminateWorkflowResponse], error)
	PauseWorkflow(context.Context, *connect.Request[workflow.PauseWorkflowRequest]) (*connect.Response[workflow.PauseWorkflowResponse], error)
	ResumeWorkflow(context.Context, *connect.Request[workflow.ResumeWorkflowRequest]) (*connect.Response[workflow.ResumeWorkflowResponse], error)
	SearchWorkflows(context.Context, *connect.Request[workflow.SearchWorkflowsRequest]) (*connect.Response[workflow.SearchWorkflowsResponse], error)
	ValidateWorkflow(context.Context, *connect.Request[workflow.ValidateWorkflowRequest]) (*connect.Response[workflow.ValidateWorkflowResponse], error)
}

// NewWorkflowServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkflowServiceHandler(svc WorkflowServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workflowServiceMethods := workflow.File_workflow_workflow_proto.Services().ByName("WorkflowService").Methods()
	workflowServiceExecuteWorkflowSourceHandler := connect.NewUnaryHandler(
		WorkflowServiceExecuteWorkflowSourceProcedure,
		svc.ExecuteWorkflowSource,
		connect.WithSchema(workflowServiceMethods.ByName("ExecuteWorkflowSource")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceExecuteWorkflowDeclarationHandler := connect.NewUnaryHandler(
		WorkflowServiceExecuteWorkflowDeclarationProcedure,
		svc.ExecuteWorkflowDeclaration,
		connect.WithSchema(workflowServiceMethods.ByName("ExecuteWorkflowDeclaration")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceGetWorkflowStatusHandler := connect.NewUnaryHandler(
		WorkflowServiceGetWorkflowStatusProcedure,
		svc.GetWorkflowStatus,
		connect.WithSchema(workflowServiceMethods.ByName("GetWorkflowStatus")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceDescribeWorkflowHandler := connect.NewUnaryHandler(
		WorkflowServiceDescribeWorkflowProcedure,
		svc.DescribeWorkflow,
		connect.WithSchema(workflowServiceMethods.ByName("DescribeWorkflow")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceListWorkflowsHandler := connect.NewUnaryHandler(
		WorkflowServiceListWorkflowsProcedure,
		svc.ListWorkflows,
		connect.WithSchema(workflowServiceMethods.ByName("ListWorkflows")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceQueryWorkflowHandler := connect.NewUnaryHandler(
		WorkflowServiceQueryWorkflowProcedure,
		svc.QueryWorkflow,
		connect.WithSchema(workflowServiceMethods.ByName("QueryWorkflow")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceQueryMonitorStatusHandler := connect.NewUnaryHandler(
		WorkflowServiceQueryMonitorStatusProcedure,
		svc.QueryMonitorStatus,
		connect.WithSchema(workflowServiceMethods.ByName("QueryMonitorStatus")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceQueryTraceHandler := connect.NewUnaryHandler(
		WorkflowServiceQueryTraceProcedure,
		svc.QueryTrace,
		connect.WithSchema(workflowServiceMethods.ByName("QueryTrace")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceCancelWorkflowHandler := connect.NewUnaryHandler(
		WorkflowServiceCancelWorkflowProcedure,
		svc.CancelWorkflow,
		connect.WithSchema(workflowServiceMethods.ByName("CancelWorkflow")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceSignalWorkflowHandler := connect.NewUnaryHandler(
		WorkflowServiceSignalWorkflowProcedure,
		svc.SignalWorkflow,
		connect.WithSchema(workflowServiceMethods.ByName("SignalWorkflow")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceTerminateWorkflowHandler := connect.NewUnaryHandler(
		WorkflowServiceTerminateWorkflowProcedure,
		svc.TerminateWorkflow,
		connect.WithSchema(workflowServiceMethods.ByName("TerminateWorkflow")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServicePauseWorkflowHandler := connect.NewUnaryHandler(
		WorkflowServicePauseWorkflowProcedure,
		svc.PauseWorkflow,
		connect.WithSchema(workflowServiceMethods.ByName("PauseWorkflow")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceResumeWorkflowHandler := connect.NewUnaryHandler(
		WorkflowServiceResumeWorkflowProcedure,
		svc.ResumeWorkflow,
		connect.WithSchema(workflowServiceMethods.ByName("ResumeWorkflow")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceSearchWorkflowsHandler := connect.NewUnaryHandler(
		WorkflowServiceSearchWorkflowsProcedure,
		svc.SearchWorkflows,
		connect.WithSchema(workflowServiceMethods.ByName("SearchWorkflows")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceValidateWorkflowHandler := connect.NewUnaryHandler(
		WorkflowServiceValidateWorkflowProcedure,
		svc.ValidateWorkflow,
		connect.WithSchema(workflowServiceMethods.ByName("ValidateWorkflow")),
		connect.WithHandlerOptions(opts...),
	)
	return "/workflow.WorkflowService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkflowServiceExecuteWorkflowSourceProcedure:
			workflowServiceExecuteWorkflowSourceHandler.ServeHTTP(w, r)
		case WorkflowServiceExecuteWorkflowDeclarationProcedure:
			workflowServiceExecuteWorkflowDeclarationHandler.ServeHTTP(w, r)
		case WorkflowServiceGetWorkflowStatusProcedure:
			workflowServiceGetWorkflowStatusHandler.ServeHTTP(w, r)
		case WorkflowServiceDescribeWorkflowProcedure:
			workflowServiceDescribeWorkflowHandler.ServeHTTP(w, r)
		case WorkflowServiceListWorkflowsProcedure:
			workflowServiceListWorkflowsHandler.ServeHTTP(w, r)
		case WorkflowServiceQueryWorkflowProcedure:
			workflowServiceQueryWorkflowHandler.ServeHTTP(w, r)
		case WorkflowServiceQueryMonitorStatusProcedure:
			workflowServiceQueryMonitorStatusHandler.ServeHTTP(w, r)
		case WorkflowServiceQueryTraceProcedure:
			workflowServiceQueryTraceHandler.ServeHTTP(w, r)
		case WorkflowServiceCancelWorkflowProcedure:
			workflowServiceCancelWorkflowHandler.ServeHTTP(w, r)
		case WorkflowServiceSignalWorkflowProcedure:
			workflowServiceSignalWorkflowHandler.ServeHTTP(w, r)
		case WorkflowServiceTerminateWorkflowProcedure:
			workflowServiceTerminateWorkflowHandler.ServeHTTP(w, r)
		case WorkflowServicePauseWorkflowProcedure:
			workflowServicePauseWorkflowHandler.ServeHTTP(w, r)
		case WorkflowServiceResumeWorkflowProcedure:
			workflowServiceResumeWorkflowHandler.ServeHTTP(w, r)
		case WorkflowServiceSearchWorkflowsProcedure:
			workflowServiceSearchWorkflowsHandler.ServeHTTP(w, r)
		case WorkflowServiceValidateWorkflowProcedure:
			workflowServiceValidateWorkflowHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkflowServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkflowServiceHandler struct{}

func (UnimplementedWorkflowServiceHandler) ExecuteWorkflowSource(context.Context, *connect.Request[workflow.ExecuteWorkflowSourceRequest]) (*connect.Response[workflow.ExecuteWorkflowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.ExecuteWorkflowSource is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) ExecuteWorkflowDeclaration(context.Context, *connect.Request[workflow.ExecuteWorkflowDeclarationRequest]) (*connect.Response[workflow.ExecuteWorkflowDeclarationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.ExecuteWorkflowDeclaration is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) GetWorkflowStatus(context.Context, *connect.Request[workflow.GetWorkflowStatusRequest]) (*connect.Response[workflow.GetWorkflowStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.GetWorkflowStatus is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) DescribeWorkflow(context.Context, *connect.Request[workflow.DescribeWorkflowRequest]) (*connect.Response[workflow.DescribeWorkflowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.DescribeWorkflow is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) ListWorkflows(context.Context, *connect.Request[workflow.ListWorkflowsRequest]) (*connect.Response[workflow.ListWorkflowsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.ListWorkflows is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) QueryWorkflow(context.Context, *connect.Request[workflow.QueryWorkflowRequest]) (*connect.Response[workflow.QueryWorkflowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.QueryWorkflow is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) QueryMonitorStatus(context.Context, *connect.Request[workflow.QueryMonitorStatusRequest]) (*connect.Response[workflow.QueryMonitorStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.QueryMonitorStatus is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) QueryTrace(context.Context, *connect.Request[workflow.QueryTraceRequest]) (*connect.Response[workflow.QueryTraceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.QueryTrace is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) CancelWorkflow(context.Context, *connect.Request[workflow.CancelWorkflowRequest]) (*connect.Response[workflow.CancelWorkflowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.CancelWorkflow is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) SignalWorkflow(context.Context, *connect.Request[workflow.SignalWorkflowRequest]) (*connect.Response[workflow.SignalWorkflowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.SignalWorkflow is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) TerminateWorkflow(context.Context, *connect.Request[workflow.TerminateWorkflowRequest]) (*connect.Response[workflow.TerminateWorkflowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.TerminateWorkflow is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) PauseWorkflow(context.Context, *connect.Request[workflow.PauseWorkflowRequest]) (*connect.Response[workflow.PauseWorkflowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.PauseWorkflow is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) ResumeWorkflow(context.Context, *connect.Request[workflow.ResumeWorkflowRequest]) (*connect.Response[workflow.ResumeWorkflowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.ResumeWorkflow is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) SearchWorkflows(context.Context, *connect.Request[workflow.SearchWorkflowsRequest]) (*connect.Response[workflow.SearchWorkflowsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.SearchWorkflows is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) ValidateWorkflow(context.Context, *connect.Request[workflow.ValidateWorkflowRequest]) (*connect.Response[workflow.ValidateWorkflowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.WorkflowService.ValidateWorkflow is not implemented"))
}
